merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('brands/', views.brand_list, name="brand_list"),
    path('brands/<int:brand_id>/', views.brand_detail, name="brand_detail"),
    path('about-us', views.about),
    path('contact-us', views.contact),
    path('listings', views.listing),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxLengthValidator


class Brand(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    name = models.fields.CharField(max_length=100)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField()
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = "Records"
        CLOTHING = "Clothing"
        POSTER = "Poster"
        MISCELLANEOUS = "Miscellaneous"

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=5000)
    is_sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True, blank=True)
    type = models.fields.CharField(choices=Type.choices, max_length=20)
    brand = models.ForeignKey(Brand,on_delete=models.SET_NULL, null=True,)

    def __str__(self):
        return f'{self.title}'

merchex/listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Brand
from listings.models import Listing


def brand_list(request):
    brands = Brand.objects.all()
    return render(request,
                  "listings/brand_list.html",
                  {"brands": brands})


def brand_detail(request, brand_id):
    brand = Brand.objects.get(id=brand_id)
    return render(request,
                  "listings/brand_detail.html",
                  context={'brand': brand})


def about(request):
    return HttpResponse('<h1>About us <h1/>')


def contact(request):
    return render(request, 'listings/contact.html')


def listing(request):
    listings = Listing.objects.all()
    return render(request,
                  "listings/listing.html",
                  {"listings": listings})

merchex/listings/templates/listings/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Python Project</title>
      <link rel="stylesheet" href="{% static 'listings/style.css' %}" />
</head>
<body>
    <nav>
     <a href="{% url 'brand_list' %}">Groupes</a>
   </nav>
    {%block content %} {% endblock %}
</body>
</html>

merchex/listings/templates/listings/brand_detail.html
{% extends 'listings/base.html' %}

{% block content %}
 <h2>{{ brand.name }}</h2>

<ul>
 <li>Genre : {{ brand.get_genre_display }}</li>
 <li>Année de formation : {{ brand.year_formed }}</li>
 <li>Actif : {{ brand.active|yesno }}</li>
 {% if brand.official_homepage %}
 <a href="{{ brand.official_homepage }}">{{ brand.official_homepage }}</a>

 {% endif %}
</ul>

<p>{{ brand.biography }}</p>
<a href="{% url 'brand_list' %}" > Voir tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/brand_list.html
{% extends "listings/base.html" %}
{% block content %}
  <h1>Hello Django !</h1>
  <p>My favorites brands are : </p>
    <ul>
        {% for brand in brands %}
            <li>
                <a href="{% url 'brand_detail' brand.id %}">{{brand.name|upper}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

merchex/listings/templates/listings/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contacts</title>
</head>
<body>
    <h1>Contact Page</h1>
    <p>Thank you for your support</p>
</body>
</html>

merchex/listings/templates/listings/listing.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Hello Django !</h1>
    <p>Listings {{listings|length}}: </p>
    <ul>
        {% for listing in listings %}
            <li>{{listing.title}}</li>
        {% endfor %}
    </ul>
{% endblock %}